version: "3.9"

services:
  web:
    build:
      # context is the project directory
      context: ../
      # dockerfile is relative to the context
      dockerfile: ./docker/Dockerfile
    image: ${IMAGE_TAG}
    ports:
      - "${APP_PORT}:${HOST_PORT}"
