docs_dir: "src/docs"
site_name: "Hello Cloud"
site_url: "https://github.com/ericis/hello-cloud/#readme"
site_author: "Ourchitecture"
copyright: "Creative Commons Zero v1.0 Universal"
theme:
  name: "material"
  logo: "img/logo.png"
  favicon: "img/favicon.png"
  features:
    - "header.autohide"
nav:
  - "Home": "index.md"
  - "Web Services":
      - "Java with SpringBoot": "./services/java-springboot.md"
      - "NodeJS with ExpressJS": "./services/nodejs-expressjs.md"
  - "Docker":
      - "hello-world/our-hello-java-springboot-webapi": "./services/java-springboot.md"
      - "hello-world/our-hello-nodejs-expressjs-webapi": "./services/nodejs-expressjs.md"
  - "Contribute": "contribute.md"
  - "License": "license.md"
  - "Code (GitHub)": "https://github.com/ericis/hello-cloud/"
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/ericis/hello-cloud/"
      name: "GitHub"
