docs_dir: "src/docs"
site_name: "Hello Cloud"
site_url: "https://github.com/ericis/hello-cloud/#readme"
repo_url: "https://github.com/ericis/hello-cloud/#readme"
repo_name: ericis/hello-cloud
site_author: "Ourchitecture"
copyright: "Creative Commons Zero v1.0 Universal"
theme:
  name: "material"
  custom_dir: "./src/mkdocs"
  logo: "img/logo.png"
  favicon: "img/favicon.png"
  palette:
    - scheme: "slate"
      primary: "blue"
      accent: "deep orange"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to light mode"
    - scheme: "default"
      primary: "blue grey"
      accent: "light blue"
      toggle:
        icon: "material/weather-night"
        name: "Switch to dark mode"
  features:
    - "header.autohide"
    - "navigation.indexes"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.top"
    - "navigation.sections"
    - "toc.integrate"
nav:
  - "Home": "index.md"
  - "Projects":
      - ".NET": "./services/dotnet.md"
      - "Java with SpringBoot": "./services/java-springboot.md"
      - "NodeJS with ExpressJS": "./services/nodejs-expressjs.md"
  - "Roadmap": "roadmap.md"
  - "Contribute": "contribute.md"
  - "Comments": "comments.md"
  - "License": "license.md"
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/ericis/hello-cloud/"
      name: "GitHub"
  disqus: hello-cloud
  analytics:
    provider: google
    property: G-YWLCJCMGFX
