docs_dir: "src/docs"
site_name: "Hello Cloud"
site_url: "https://www.ourchitecture.io/hello-cloud/"
repo_url: "https://github.com/ourchitecture/hello-cloud/#readme"
repo_name: ourchitecture/hello-cloud
edit_uri: "edit/main/src/docs"
site_author: "Ourchitecture"
copyright: "Creative Commons Zero v1.0 Universal"
theme:
  name: "material"
  custom_dir: "./src/mkdocs/overrides"
  logo: "img/logo.png"
  favicon: "img/favicon.png"
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: "slate"
      primary: "blue"
      accent: "deep orange"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to light mode"
    - scheme: "default"
      primary: "blue grey"
      accent: "light blue"
      toggle:
        icon: "material/weather-night"
        name: "Switch to dark mode"
  features:
    - "header.autohide"
    - "navigation.indexes"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.top"
    - "navigation.sections"
    - "toc.integrate"
nav:
  - "Home": "index.md"
  - "Clouds": "clouds.md"
  - "Projects":
      - ".NET": "./services/dotnet.md"
      - "Java with SpringBoot": "./services/java-springboot.md"
      - "Kotlin with SpringBoot": "./services/kotlin-springboot.md"
      - "NodeJS with ExpressJS": "./services/nodejs-expressjs.md"
  - "DevOps": "devops.md"
  - "Roadmap": "roadmap.md"
  - "Contribute": "contribute.md"
  - "Comments": "comments.md"
  - "License": "license.md"
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/ourchitecture/hello-cloud/"
      name: "GitHub"
  disqus: "hello-cloud"
  analytics:
    provider: "google"
    property: "G-YWLCJCMGFX"
  generator: false
extra_css:
  - "assets/stylesheets/extra.css"
extra_javascript:
  - "https://unpkg.com/mermaid@8.5.2/dist/mermaid.min.js"
markdown_extensions:
  - "admonition"
  - "attr_list"
  - "def_list"
  - "md_in_html"
  - "meta"
  - "pymdownx.details"
  - "pymdownx.emoji":
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - "pymdownx.highlight"
  - "pymdownx.inlinehilite"
  - "pymdownx.keys"
  - "pymdownx.magiclink"
  - "pymdownx.snippets"
  - "pymdownx.superfences":
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - "pymdownx.tasklist":
      custom_checkbox: true
plugins:
  - mermaid2
