docs_dir: "src/docs"
site_name: "Hello Cloud"
site_url: "https://github.com/ericis/hello-cloud/#readme"
site_author: "Ourchitecture"
copyright: "Creative Commons Zero v1.0 Universal"
theme:
  name: "material"
  features:
    - "header.autohide"
nav:
  - "Home": "index.md"
  - "Contribute": "contribute.md"
  - "Code (GitHub)": "https://github.com/ericis/hello-cloud/"
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/ericis/hello-cloud/"
      name: "GitHub"
