name: documentation

on:
  push:
    branches: [main]
    paths:
      - "makefile"
      - "mkdocs.yml"
      - ".github/workflows/documentation.yml"
      - "src/docs/**"
  pull_request:
    branches: [main]
    paths:
      - "makefile"
      - "mkdocs.yml"
      - ".github/workflows/documentation.yml"
      - "src/docs/**"

jobs:
  generate:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: documentation
        run: |
          make install-docs
          sudo chown -R $(whoami) ./docs

      - name: Debug Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "EVENT: ${{ github.event_name }}"
          echo "SOURCE: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "REPO: ${{ github.repository }}"

      - name: Debug Push
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "EVENT: ${{ github.event_name }}"
          echo "SOURCE: ${{ github.event.push.head.repo.full_name }}"
          echo "REPO: ${{ github.repository }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        # only:
        # - push, not pr
        # - primary repo, not forks
        if: ${{ github.event_name == 'push' }}
        with:
          title: "docs: auto-generated documentation"
          signoff: true
          commit-message: "docs: auto-generated documentation [skip ci]"
          body: "Automatically generated documentation that requires a PR, because the main branch is protected."
          labels: "documentation"
          reviewers: "ericis"
          assignees: "ericis"
