name: documentation

on:
  push:
    branches: [main]
    paths:
      - "makefile"
      - "mkdocs.yml"
      - ".github/workflows/documentation.yml"
      - "src/docs/**"
  pull_request:
    branches: [main]
    paths:
      - "makefile"
      - "mkdocs.yml"
      - ".github/workflows/documentation.yml"
      - "src/docs/**"

jobs:
  generate:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: sync
        run: git pull

      - name: documentation
        run: make install-docs

      - name: publish
        if: ${{ github.event_name == 'push' }}
        run: |
          git config user.name our-github-actions
          git config user.email ericis@users.noreply.github.com
          git add .
          git commit -m 'docs: auto-generate documentation [skip ci]'
          git pull
          git push
