name: documentation

on:
  push:
    branches: [main]
    paths:
      - "makefile"
      - "mkdocs.yml"
      - ".github/workflows/documentation.yml"
      - "src/docs/**"
  pull_request:
    branches: [main]
    paths:
      - "makefile"
      - "mkdocs.yml"
      - ".github/workflows/documentation.yml"
      - "src/docs/**"

jobs:
  generate:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: documentation
        run: |
          make install-docs
          sudo chown -R $(whoami) ./docs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        # Avoid creating another PR to the forked repo when
        # merging auto-docs back into forks can trigger a
        # "push" build action from the fork's "main" branch.
        # - push, not pull_request
        # - primary repo, not forks
        # examples of the issue can be seen here:
        # - "Debug push": https://github.com/ourchitecture/hello-cloud/runs/4733230834?check_suite_focus=true
        # - Forked "Debug push": https://github.com/ericis/hello-cloud/runs/4733253190?check_suite_focus=true
        if: ${{ github.event_name == 'push' && github.repository == 'ourchitecture/hello-cloud' }}
        with:
          title: "docs: auto-generated documentation"
          signoff: true
          commit-message: "docs: auto-generated documentation [skip ci]"
          body: "Automatically generated documentation that requires a PR, because the main branch is protected."
          labels: "documentation"
          reviewers: "ericis"
          assignees: "ericis"
