name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make

      - name: commit
        run: |
          git config user.name 'Ourchitecture Github Actions'
          git config user.email 'ericis@users.noreply.github.com'
          git add ${GITHUB_WORKSPACE}/docs
          git commit -m 'docs: auto-generate documentation [skip ci]'
          git pull
          git push
